// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_TEXT  MessageType = 0
	MessageType_MESSAGE_TYPE_IMAGE MessageType = 1
	MessageType_MESSAGE_TYPE_VIDEO MessageType = 2
	MessageType_MESSAGE_TYPE_AUDIO MessageType = 3
	MessageType_MESSAGE_TYPE_FILE  MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_TEXT",
		1: "MESSAGE_TYPE_IMAGE",
		2: "MESSAGE_TYPE_VIDEO",
		3: "MESSAGE_TYPE_AUDIO",
		4: "MESSAGE_TYPE_FILE",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_TEXT":  0,
		"MESSAGE_TYPE_IMAGE": 1,
		"MESSAGE_TYPE_VIDEO": 2,
		"MESSAGE_TYPE_AUDIO": 3,
		"MESSAGE_TYPE_FILE":  4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

type RoomType int32

const (
	RoomType_ROOM_TYPE_DM    RoomType = 0
	RoomType_ROOM_TYPE_GROUP RoomType = 1
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOM_TYPE_DM",
		1: "ROOM_TYPE_GROUP",
	}
	RoomType_value = map[string]int32{
		"ROOM_TYPE_DM":    0,
		"ROOM_TYPE_GROUP": 1,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[1].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[1]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

// EventType differentiates data messages from control events inside the stream.
// Control events are never stored in Cassandra.
type EventType int32

const (
	EventType_EVENT_TYPE_MESSAGE      EventType = 0 // normal chat message (default)
	EventType_EVENT_TYPE_TYPING_START EventType = 1 // user started typing
	EventType_EVENT_TYPE_TYPING_STOP  EventType = 2 // user stopped typing
	EventType_EVENT_TYPE_READ_RECEIPT EventType = 3 // user has read up to message_id
	EventType_EVENT_TYPE_REACTION     EventType = 4 // emoji reaction on a message
	EventType_EVENT_TYPE_DELETE       EventType = 5 // soft-delete a message
	EventType_EVENT_TYPE_PRESENCE     EventType = 6 // online / last-seen update
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_MESSAGE",
		1: "EVENT_TYPE_TYPING_START",
		2: "EVENT_TYPE_TYPING_STOP",
		3: "EVENT_TYPE_READ_RECEIPT",
		4: "EVENT_TYPE_REACTION",
		5: "EVENT_TYPE_DELETE",
		6: "EVENT_TYPE_PRESENCE",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_MESSAGE":      0,
		"EVENT_TYPE_TYPING_START": 1,
		"EVENT_TYPE_TYPING_STOP":  2,
		"EVENT_TYPE_READ_RECEIPT": 3,
		"EVENT_TYPE_REACTION":     4,
		"EVENT_TYPE_DELETE":       5,
		"EVENT_TYPE_PRESENCE":     6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

// MessageStatus tracks the delivery lifecycle of a sent message.
type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_SENDING   MessageStatus = 0 // client optimistic state
	MessageStatus_MESSAGE_STATUS_SENT      MessageStatus = 1 // server acknowledged
	MessageStatus_MESSAGE_STATUS_DELIVERED MessageStatus = 2 // at least one recipient device received it
	MessageStatus_MESSAGE_STATUS_READ      MessageStatus = 3 // all recipients have opened it
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_SENDING",
		1: "MESSAGE_STATUS_SENT",
		2: "MESSAGE_STATUS_DELIVERED",
		3: "MESSAGE_STATUS_READ",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_SENDING":   0,
		"MESSAGE_STATUS_SENT":      1,
		"MESSAGE_STATUS_DELIVERED": 2,
		"MESSAGE_STATUS_READ":      3,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[3].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[3]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

type ClientMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // client-generated UUID
	Text           string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	SentAtUnixMs   int64                  `protobuf:"varint,5,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	Type           MessageType            `protobuf:"varint,6,opt,name=type,proto3,enum=chat.v1.MessageType" json:"type,omitempty"`
	MediaKey       string                 `protobuf:"bytes,7,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	MediaName      string                 `protobuf:"bytes,8,opt,name=media_name,json=mediaName,proto3" json:"media_name,omitempty"`
	MediaSizeBytes int64                  `protobuf:"varint,9,opt,name=media_size_bytes,json=mediaSizeBytes,proto3" json:"media_size_bytes,omitempty"`
	MediaMimeType  string                 `protobuf:"bytes,10,opt,name=media_mime_type,json=mediaMimeType,proto3" json:"media_mime_type,omitempty"`
	// Control events (set event_type to non-zero to send a control event)
	EventType EventType `protobuf:"varint,11,opt,name=event_type,json=eventType,proto3,enum=chat.v1.EventType" json:"event_type,omitempty"`
	// Reply thread — set to parent message_id to create a threaded reply
	ReplyToMessageId string `protobuf:"bytes,12,opt,name=reply_to_message_id,json=replyToMessageId,proto3" json:"reply_to_message_id,omitempty"`
	// For EVENT_TYPE_REACTION: the emoji to add/remove
	ReactionEmoji string `protobuf:"bytes,13,opt,name=reaction_emoji,json=reactionEmoji,proto3" json:"reaction_emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ClientMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClientMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ClientMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ClientMessage) GetSentAtUnixMs() int64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

func (x *ClientMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_TEXT
}

func (x *ClientMessage) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

func (x *ClientMessage) GetMediaName() string {
	if x != nil {
		return x.MediaName
	}
	return ""
}

func (x *ClientMessage) GetMediaSizeBytes() int64 {
	if x != nil {
		return x.MediaSizeBytes
	}
	return 0
}

func (x *ClientMessage) GetMediaMimeType() string {
	if x != nil {
		return x.MediaMimeType
	}
	return ""
}

func (x *ClientMessage) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_MESSAGE
}

func (x *ClientMessage) GetReplyToMessageId() string {
	if x != nil {
		return x.ReplyToMessageId
	}
	return ""
}

func (x *ClientMessage) GetReactionEmoji() string {
	if x != nil {
		return x.ReactionEmoji
	}
	return ""
}

type ServerMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoomId            string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId         string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text              string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	SentAtUnixMs      int64                  `protobuf:"varint,5,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	DeliveredAtUnixMs int64                  `protobuf:"varint,6,opt,name=delivered_at_unix_ms,json=deliveredAtUnixMs,proto3" json:"delivered_at_unix_ms,omitempty"`
	Type              MessageType            `protobuf:"varint,7,opt,name=type,proto3,enum=chat.v1.MessageType" json:"type,omitempty"`
	MediaKey          string                 `protobuf:"bytes,8,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	MediaName         string                 `protobuf:"bytes,9,opt,name=media_name,json=mediaName,proto3" json:"media_name,omitempty"`
	MediaSizeBytes    int64                  `protobuf:"varint,10,opt,name=media_size_bytes,json=mediaSizeBytes,proto3" json:"media_size_bytes,omitempty"`
	MediaMimeType     string                 `protobuf:"bytes,11,opt,name=media_mime_type,json=mediaMimeType,proto3" json:"media_mime_type,omitempty"`
	MediaUrl          string                 `protobuf:"bytes,12,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"` // presigned GET URL (short-lived)
	// Control events
	EventType EventType `protobuf:"varint,13,opt,name=event_type,json=eventType,proto3,enum=chat.v1.EventType" json:"event_type,omitempty"`
	// Reply thread
	ReplyToMessageId string `protobuf:"bytes,14,opt,name=reply_to_message_id,json=replyToMessageId,proto3" json:"reply_to_message_id,omitempty"`
	// Reaction
	ReactionEmoji string `protobuf:"bytes,15,opt,name=reaction_emoji,json=reactionEmoji,proto3" json:"reaction_emoji,omitempty"`
	// Edit / delete
	IsDeleted      bool  `protobuf:"varint,16,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	EditedAtUnixMs int64 `protobuf:"varint,17,opt,name=edited_at_unix_ms,json=editedAtUnixMs,proto3" json:"edited_at_unix_ms,omitempty"` // 0 = never edited
	// Delivery status (set by server, reflects aggregate across recipients)
	Status MessageStatus `protobuf:"varint,18,opt,name=status,proto3,enum=chat.v1.MessageStatus" json:"status,omitempty"`
	// Presence (used with EVENT_TYPE_PRESENCE)
	IsOnline       bool  `protobuf:"varint,19,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	LastSeenUnixMs int64 `protobuf:"varint,20,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ServerMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ServerMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ServerMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ServerMessage) GetSentAtUnixMs() int64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

func (x *ServerMessage) GetDeliveredAtUnixMs() int64 {
	if x != nil {
		return x.DeliveredAtUnixMs
	}
	return 0
}

func (x *ServerMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_TEXT
}

func (x *ServerMessage) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

func (x *ServerMessage) GetMediaName() string {
	if x != nil {
		return x.MediaName
	}
	return ""
}

func (x *ServerMessage) GetMediaSizeBytes() int64 {
	if x != nil {
		return x.MediaSizeBytes
	}
	return 0
}

func (x *ServerMessage) GetMediaMimeType() string {
	if x != nil {
		return x.MediaMimeType
	}
	return ""
}

func (x *ServerMessage) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *ServerMessage) GetEventType() EventType {
	if x != nil {
		return x.EventType
	}
	return EventType_EVENT_TYPE_MESSAGE
}

func (x *ServerMessage) GetReplyToMessageId() string {
	if x != nil {
		return x.ReplyToMessageId
	}
	return ""
}

func (x *ServerMessage) GetReactionEmoji() string {
	if x != nil {
		return x.ReactionEmoji
	}
	return ""
}

func (x *ServerMessage) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *ServerMessage) GetEditedAtUnixMs() int64 {
	if x != nil {
		return x.EditedAtUnixMs
	}
	return 0
}

func (x *ServerMessage) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_SENDING
}

func (x *ServerMessage) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *ServerMessage) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

type GetMessagesRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RoomId string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // requesting user (for auth / read-receipt update)
	Limit  int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                // max messages to return (default 50, max 200)
	// Pagination: return messages older than this timestamp
	BeforeUnixMs  int64 `protobuf:"varint,4,opt,name=before_unix_ms,json=beforeUnixMs,proto3" json:"before_unix_ms,omitempty"` // 0 = from now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessagesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessagesRequest) GetBeforeUnixMs() int64 {
	if x != nil {
		return x.BeforeUnixMs
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ServerMessage       `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"` // true if older messages exist
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessagesResponse) GetMessages() []*ServerMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSizeBytes int64                  `protobuf:"varint,5,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *UploadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadRequest) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

type UploadResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MediaKey        string                 `protobuf:"bytes,1,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	UploadUrl       string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,3,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *UploadResponse) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

func (x *UploadResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *UploadResponse) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

type GetDownloadUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MediaKey      string                 `protobuf:"bytes,2,opt,name=media_key,json=mediaKey,proto3" json:"media_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadUrlRequest) Reset() {
	*x = GetDownloadUrlRequest{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlRequest) ProtoMessage() {}

func (x *GetDownloadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetDownloadUrlRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDownloadUrlRequest) GetMediaKey() string {
	if x != nil {
		return x.MediaKey
	}
	return ""
}

type GetDownloadUrlResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,2,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDownloadUrlResponse) Reset() {
	*x = GetDownloadUrlResponse{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadUrlResponse) ProtoMessage() {}

func (x *GetDownloadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadUrlResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadUrlResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetDownloadUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetDownloadUrlResponse) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedBy     string                 `protobuf:"bytes,1,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          RoomType               `protobuf:"varint,3,opt,name=type,proto3,enum=chat.v1.RoomType" json:"type,omitempty"`
	MemberIds     []string               `protobuf:"bytes,4,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRoomRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_DM
}

func (x *CreateRoomRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // batch lookup
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *GetPresenceRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type PresenceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsOnline       bool                   `protobuf:"varint,2,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	LastSeenUnixMs int64                  `protobuf:"varint,3,opt,name=last_seen_unix_ms,json=lastSeenUnixMs,proto3" json:"last_seen_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PresenceInfo) Reset() {
	*x = PresenceInfo{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceInfo) ProtoMessage() {}

func (x *PresenceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceInfo.ProtoReflect.Descriptor instead.
func (*PresenceInfo) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *PresenceInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceInfo) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *PresenceInfo) GetLastSeenUnixMs() int64 {
	if x != nil {
		return x.LastSeenUnixMs
	}
	return 0
}

type GetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*PresenceInfo        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceResponse) Reset() {
	*x = GetPresenceResponse{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceResponse) ProtoMessage() {}

func (x *GetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *GetPresenceResponse) GetUsers() []*PresenceInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\achat.v1\"\xdc\x03\n" +
	"\rClientMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12%\n" +
	"\x0fsent_at_unix_ms\x18\x05 \x01(\x03R\fsentAtUnixMs\x12(\n" +
	"\x04type\x18\x06 \x01(\x0e2\x14.chat.v1.MessageTypeR\x04type\x12\x1b\n" +
	"\tmedia_key\x18\a \x01(\tR\bmediaKey\x12\x1d\n" +
	"\n" +
	"media_name\x18\b \x01(\tR\tmediaName\x12(\n" +
	"\x10media_size_bytes\x18\t \x01(\x03R\x0emediaSizeBytes\x12&\n" +
	"\x0fmedia_mime_type\x18\n" +
	" \x01(\tR\rmediaMimeType\x121\n" +
	"\n" +
	"event_type\x18\v \x01(\x0e2\x12.chat.v1.EventTypeR\teventType\x12-\n" +
	"\x13reply_to_message_id\x18\f \x01(\tR\x10replyToMessageId\x12%\n" +
	"\x0ereaction_emoji\x18\r \x01(\tR\rreactionEmoji\"\xec\x05\n" +
	"\rServerMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12%\n" +
	"\x0fsent_at_unix_ms\x18\x05 \x01(\x03R\fsentAtUnixMs\x12/\n" +
	"\x14delivered_at_unix_ms\x18\x06 \x01(\x03R\x11deliveredAtUnixMs\x12(\n" +
	"\x04type\x18\a \x01(\x0e2\x14.chat.v1.MessageTypeR\x04type\x12\x1b\n" +
	"\tmedia_key\x18\b \x01(\tR\bmediaKey\x12\x1d\n" +
	"\n" +
	"media_name\x18\t \x01(\tR\tmediaName\x12(\n" +
	"\x10media_size_bytes\x18\n" +
	" \x01(\x03R\x0emediaSizeBytes\x12&\n" +
	"\x0fmedia_mime_type\x18\v \x01(\tR\rmediaMimeType\x12\x1b\n" +
	"\tmedia_url\x18\f \x01(\tR\bmediaUrl\x121\n" +
	"\n" +
	"event_type\x18\r \x01(\x0e2\x12.chat.v1.EventTypeR\teventType\x12-\n" +
	"\x13reply_to_message_id\x18\x0e \x01(\tR\x10replyToMessageId\x12%\n" +
	"\x0ereaction_emoji\x18\x0f \x01(\tR\rreactionEmoji\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x10 \x01(\bR\tisDeleted\x12)\n" +
	"\x11edited_at_unix_ms\x18\x11 \x01(\x03R\x0eeditedAtUnixMs\x12.\n" +
	"\x06status\x18\x12 \x01(\x0e2\x16.chat.v1.MessageStatusR\x06status\x12\x1b\n" +
	"\tis_online\x18\x13 \x01(\bR\bisOnline\x12)\n" +
	"\x11last_seen_unix_ms\x18\x14 \x01(\x03R\x0elastSeenUnixMs\"\x82\x01\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12$\n" +
	"\x0ebefore_unix_ms\x18\x04 \x01(\x03R\fbeforeUnixMs\"d\n" +
	"\x13GetMessagesResponse\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.chat.v1.ServerMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xa3\x01\n" +
	"\rUploadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12&\n" +
	"\x0ffile_size_bytes\x18\x05 \x01(\x03R\rfileSizeBytes\"y\n" +
	"\x0eUploadResponse\x12\x1b\n" +
	"\tmedia_key\x18\x01 \x01(\tR\bmediaKey\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\x12+\n" +
	"\x12expires_at_unix_ms\x18\x03 \x01(\x03R\x0fexpiresAtUnixMs\"M\n" +
	"\x15GetDownloadUrlRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmedia_key\x18\x02 \x01(\tR\bmediaKey\"W\n" +
	"\x16GetDownloadUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12+\n" +
	"\x12expires_at_unix_ms\x18\x02 \x01(\x03R\x0fexpiresAtUnixMs\"\x8c\x01\n" +
	"\x11CreateRoomRequest\x12\x1d\n" +
	"\n" +
	"created_by\x18\x01 \x01(\tR\tcreatedBy\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.chat.v1.RoomTypeR\x04type\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x04 \x03(\tR\tmemberIds\"A\n" +
	"\x12CreateRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"/\n" +
	"\x12GetPresenceRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"o\n" +
	"\fPresenceInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tis_online\x18\x02 \x01(\bR\bisOnline\x12)\n" +
	"\x11last_seen_unix_ms\x18\x03 \x01(\x03R\x0elastSeenUnixMs\"B\n" +
	"\x13GetPresenceResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.chat.v1.PresenceInfoR\x05users*\x83\x01\n" +
	"\vMessageType\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x00\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_VIDEO\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_AUDIO\x10\x03\x12\x15\n" +
	"\x11MESSAGE_TYPE_FILE\x10\x04*1\n" +
	"\bRoomType\x12\x10\n" +
	"\fROOM_TYPE_DM\x10\x00\x12\x13\n" +
	"\x0fROOM_TYPE_GROUP\x10\x01*\xc2\x01\n" +
	"\tEventType\x12\x16\n" +
	"\x12EVENT_TYPE_MESSAGE\x10\x00\x12\x1b\n" +
	"\x17EVENT_TYPE_TYPING_START\x10\x01\x12\x1a\n" +
	"\x16EVENT_TYPE_TYPING_STOP\x10\x02\x12\x1b\n" +
	"\x17EVENT_TYPE_READ_RECEIPT\x10\x03\x12\x17\n" +
	"\x13EVENT_TYPE_REACTION\x10\x04\x12\x15\n" +
	"\x11EVENT_TYPE_DELETE\x10\x05\x12\x17\n" +
	"\x13EVENT_TYPE_PRESENCE\x10\x06*{\n" +
	"\rMessageStatus\x12\x1a\n" +
	"\x16MESSAGE_STATUS_SENDING\x10\x00\x12\x17\n" +
	"\x13MESSAGE_STATUS_SENT\x10\x01\x12\x1c\n" +
	"\x18MESSAGE_STATUS_DELIVERED\x10\x02\x12\x17\n" +
	"\x13MESSAGE_STATUS_READ\x10\x032\xb9\x03\n" +
	"\vChatService\x12:\n" +
	"\x04Chat\x12\x16.chat.v1.ClientMessage\x1a\x16.chat.v1.ServerMessage(\x010\x01\x12E\n" +
	"\n" +
	"CreateRoom\x12\x1a.chat.v1.CreateRoomRequest\x1a\x1b.chat.v1.CreateRoomResponse\x12H\n" +
	"\vGetMessages\x12\x1b.chat.v1.GetMessagesRequest\x1a\x1c.chat.v1.GetMessagesResponse\x12@\n" +
	"\rRequestUpload\x12\x16.chat.v1.UploadRequest\x1a\x17.chat.v1.UploadResponse\x12Q\n" +
	"\x0eGetDownloadUrl\x12\x1e.chat.v1.GetDownloadUrlRequest\x1a\x1f.chat.v1.GetDownloadUrlResponse\x12H\n" +
	"\vGetPresence\x12\x1b.chat.v1.GetPresenceRequest\x1a\x1c.chat.v1.GetPresenceResponseB\x18Z\x16chat-service/app/pb;pbb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_chat_proto_goTypes = []any{
	(MessageType)(0),               // 0: chat.v1.MessageType
	(RoomType)(0),                  // 1: chat.v1.RoomType
	(EventType)(0),                 // 2: chat.v1.EventType
	(MessageStatus)(0),             // 3: chat.v1.MessageStatus
	(*ClientMessage)(nil),          // 4: chat.v1.ClientMessage
	(*ServerMessage)(nil),          // 5: chat.v1.ServerMessage
	(*GetMessagesRequest)(nil),     // 6: chat.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil),    // 7: chat.v1.GetMessagesResponse
	(*UploadRequest)(nil),          // 8: chat.v1.UploadRequest
	(*UploadResponse)(nil),         // 9: chat.v1.UploadResponse
	(*GetDownloadUrlRequest)(nil),  // 10: chat.v1.GetDownloadUrlRequest
	(*GetDownloadUrlResponse)(nil), // 11: chat.v1.GetDownloadUrlResponse
	(*CreateRoomRequest)(nil),      // 12: chat.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),     // 13: chat.v1.CreateRoomResponse
	(*GetPresenceRequest)(nil),     // 14: chat.v1.GetPresenceRequest
	(*PresenceInfo)(nil),           // 15: chat.v1.PresenceInfo
	(*GetPresenceResponse)(nil),    // 16: chat.v1.GetPresenceResponse
}
var file_chat_proto_depIdxs = []int32{
	0,  // 0: chat.v1.ClientMessage.type:type_name -> chat.v1.MessageType
	2,  // 1: chat.v1.ClientMessage.event_type:type_name -> chat.v1.EventType
	0,  // 2: chat.v1.ServerMessage.type:type_name -> chat.v1.MessageType
	2,  // 3: chat.v1.ServerMessage.event_type:type_name -> chat.v1.EventType
	3,  // 4: chat.v1.ServerMessage.status:type_name -> chat.v1.MessageStatus
	5,  // 5: chat.v1.GetMessagesResponse.messages:type_name -> chat.v1.ServerMessage
	1,  // 6: chat.v1.CreateRoomRequest.type:type_name -> chat.v1.RoomType
	15, // 7: chat.v1.GetPresenceResponse.users:type_name -> chat.v1.PresenceInfo
	4,  // 8: chat.v1.ChatService.Chat:input_type -> chat.v1.ClientMessage
	12, // 9: chat.v1.ChatService.CreateRoom:input_type -> chat.v1.CreateRoomRequest
	6,  // 10: chat.v1.ChatService.GetMessages:input_type -> chat.v1.GetMessagesRequest
	8,  // 11: chat.v1.ChatService.RequestUpload:input_type -> chat.v1.UploadRequest
	10, // 12: chat.v1.ChatService.GetDownloadUrl:input_type -> chat.v1.GetDownloadUrlRequest
	14, // 13: chat.v1.ChatService.GetPresence:input_type -> chat.v1.GetPresenceRequest
	5,  // 14: chat.v1.ChatService.Chat:output_type -> chat.v1.ServerMessage
	13, // 15: chat.v1.ChatService.CreateRoom:output_type -> chat.v1.CreateRoomResponse
	7,  // 16: chat.v1.ChatService.GetMessages:output_type -> chat.v1.GetMessagesResponse
	9,  // 17: chat.v1.ChatService.RequestUpload:output_type -> chat.v1.UploadResponse
	11, // 18: chat.v1.ChatService.GetDownloadUrl:output_type -> chat.v1.GetDownloadUrlResponse
	16, // 19: chat.v1.ChatService.GetPresence:output_type -> chat.v1.GetPresenceResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
